name: Auto Update Icons

on:
  schedule:
    - cron: '47 15 * * 5'
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]
        laravel: [^8.2]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Read DotEnv File
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env

      - name: Checkout dependent repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH }}
          path: ./dist

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --dev

      - name: Verify vendor/dago-icons exists
        run: |
          if [ ! -d "vendor/dago-icons" ]; then
            echo "dago-icons module is missing!"
            exit 1
          fi

      - name: Compile icons to resources directory
        if: env.CURRENT_COMMIT != env.LATEST_COMMIT
        run: ./vendor/bin/blade-icons-generate

      - name: Update commit hash in ".commit"
        if: env.CURRENT_COMMIT != env.LATEST_COMMIT
        run: echo ${{ env.LATEST_COMMIT }}>./.commit

      - name: Create PR for latest version
        if: env.CURRENT_COMMIT != env.LATEST_COMMIT
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "auto-update: update icons with the latest commit ${{ env.LATEST_COMMIT }}"
          committer: GitHub Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "chore: update icons with the latest commit v${{ env.LATEST_COMMIT }}"
          body: |
            This updates from [${{ env.CURRENT_COMMIT }}](https://github.com/${{ env.REPOSITORY }}/commit/${{ env.CURRENT_COMMIT }}) to [${{ env.LATEST_COMMIT }}](https://github.com/${{ env.REPOSITORY }}/commit/${{ env.LATEST_COMMIT }}).
            Check out the differences: [`${{ env.CURRENT_COMMIT }}` ... `${{ env.LATEST_COMMIT }}`](https://github.com/${{ env.REPOSITORY }}/compare/${{ env.CURRENT_COMMIT }}...${{ env.LATEST_COMMIT }})
          branch: feature/update-${{ env.LATEST_COMMIT }}
