name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, '8.0', 8.1, 8.2, 8.3]
        laravel: [8, 9, 10, 11]
        exclude:
          - php: 7.4
            laravel: 9
          - php: 7.4
            laravel: 10
          - php: 7.4
            laravel: 11
          - php: '8.0'
            laravel: 10
          - php: '8.0'
            laravel: 11
          - php: 8.1
            laravel: 11
          - php: 8.2
            laravel: 8
          - php: 8.3
            laravel: 8
          - php: 8.3
            laravel: 9

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --prefer-dist --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Install PHP CS Fixer
        run: composer require --dev friendsofphp/php-cs-fixer

      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix

        - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
          file_pattern: .
          repository: ${{ github.repository }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: WillanVelascoFernandez <WillanVelascoFernandez@users.noreply.github.com>
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          create_branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
